name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  windows:
    name: Windows Tauri build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable-msvc
      - run: npm ci
      - uses: tauri-apps/tauri-action@v0
        with:
          args: --debug
